name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening this issue! We will take a look into this shortly.'
        pr-message: 'Thanks for opening this PR! One of our devs will review this shortly.'
